### PR TITLE
Adding myself to 'users.md'

### LINKED ISSUE #4: Add yourself to users.md
Follow the steps given in readme.md and add yourself to the users.md file accordingly.

### PR DESCRIPTION
**Pull request by nanspro**
Fixes #4 
-Adding about myself  like Facebook Profile link, Github Profile link etc. in 'users.md'

### CODE REVIEW

**Comment by nanspro** [comment]
@Anupam-dagar  Can you review this?

**Comment by Anupam-dagar** [comment]
please star the repo

**Comment by nanspro** [comment]
@Anupam-dagar  done

**Comment by Anupam-dagar** [comment]
LGTM :+1:

**Pull request merged**
