### PR TITLE
Users page

### PR DESCRIPTION
**Pull request by ericduns**
This pull request is for the issue no. #57  

I've added an .html file (users.html) and a .css file (style.css)

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
please provide the liive link

**Comment by Anupam-dagar** [comment]
The link is giving 404 error, go to repo settings and scroll down to gh pages, enable it and paste the link provided here.

**Comment by ericduns** [comment]
apologies, I didn't realize that change would come over to the pull request. I'll post the live link shortly

**Comment by Anupam-dagar** [comment]
No need to apologize, these mistakes are common, you will get to learn from them. :smile:

**Comment by ericduns** [comment]
so this is what it looks like after I took out some of the styling: [users page](https://ericduns.github.io/users.html)

**Comment by Anupam-dagar** [comment]
@ericduns nice work but there are issues with the webpage:
1. It doesn't use jekyll and is fully static, so every user will have to add lines of code in users.html too.Make use of jekyll so when user enter details in user.md, the website automatically get updated.
2. all the content should be centered (use container), currently, it is left aligned.
3. Include footer as in home page.

**Comment by ericduns** [comment]
@Anupam-dagar Thanks! Absolutely, I will implement those changes.

**Pull request closed without merging**
