### PR TITLE
adding contribution, thanks my bro

### PR DESCRIPTION
**Pull request by ahmadbasir**
This pull request is for the issue no. #issue_no  

I make sure that before opening this pull request I have starred this repo  

Live link of gh pages for my fork is:  
[ahmadbasir](https://github.com/ahmadbasir/awesome-first-timers)

### CODE REVIEW

**Comment by ahmadbasir** [comment]
i want to fix my link, can i?

**Comment by Anupam-dagar** [comment]
@ahmadbasir make a new PR

**Comment by ahmadbasir** [comment]
ok

**Comment by ahmadbasir** [comment]
[done ](https://github.com/Anupam-dagar/awesome-first-timers/pull/81)

**Pull request merged**
