### PR TITLE
#57 Use grid to show users

### PR DESCRIPTION
**Pull request by LarryBattle**
Here's the grid. :-)

## Changes
- Added `_data/profiles.yml`.
- Added css styling in `assets/css/style.scss`
- Added `updateProfileWithUserData.js` to update the profile data at `_data/profiles.yml` with the info in `users.md`
- Added Gemfile for those wanting to run the jekyll site locally
- Changed users page from `/users` to `/profiles` to use the grid system.
- Cleanned up readme.md
- Fixed some typos in `users.md`

## Demo:
https://larrybattle.github.io/awesome-first-timers/

## Related PR
https://github.com/Anupam-dagar/awesome-first-timers/issues/57

### CODE REVIEW

**Comment by LarryBattle** [comment]
I'll rewrite it so that it doesn't modified the users.md file. Should be done in a day.

**Comment by LarryBattle** [comment]
Done. Update the description.

**Comment by Anupam-dagar** [comment]
@LarryBattle can you take a look again, it's not working after merging.

**Comment by LarryBattle** [comment]
What's the problem?
I'm able to view http://anupamdagar.me/awesome-first-timers/profiles.html
If you want the users in http://anupamdagar.me/awesome-first-timers/users.html to match http://anupamdagar.me/awesome-first-timers/profiles.html , then run the `scripts/updateProfileWithUserData.js` script I wrote. Sorry but updating the users in the view isn't an automated progress right now because there isn't a CI build system setup.

**Comment by Anupam-dagar** [comment]
My bad, opened the wrong url, thanx

**Pull request merged**
