### PR TITLE
Update users

### LINKED ISSUE #51: fix users.md
take a look here and fix users.md accordingly
http://anupamdagar.me/awesome-first-timers/users

common errors are no 2 whitespaces after each line
himanshi khandelwal's github username 
look for others by yourself

### PR DESCRIPTION
**Pull request by nicolaspascual**
fixes #51

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
provide the live link of gh pages for your fork

**Comment by nicolaspascual** [comment]
@Anupam-dagar whta gh pages link?

**Comment by Anupam-dagar** [comment]
@nicolaspascual go to settings of your repository, scroll down and you will see github pages, select source as master and on saving you will get a link.That link is the live link for your fork.

**Comment by nicolaspascual** [comment]
https://nicolaspascual.github.io/awesome-first-timers/

**Comment by Anupam-dagar** [comment]
please resolve merge conflicts

**Pull request closed without merging**
